# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  pull_request:
    branches: [ "main" ]

jobs:
  job1:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      jira_ticket_number: ${{ steps.get_jira_ticket.outputs.jira_ticket_number }}
    steps:
      - id: get_jira_ticket
        run: echo "::set-output name=jira_ticket_number::hello"
  job2:
    runs-on: ubuntu-latest
    needs: job1
    env:

    steps:
      - run: |
          echo ${{needs.job5}}
          [ -z ${{needs.job5}} ] && echo "flag=true" >> $GITHUB_ENV
          echo $flag
      - run: echo $flag


