name: CHANGE ME

on:
  pull_request:
    types:
      - labeled

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get PR labels
        id: pr-labels
        uses: joerick/pr-labels-action@v1.0.6
      - run: echo "HEY"
        if: contains(steps.pr-labels.outputs.labels, 'storefront')
      - run: echo "${{toJSON(github.event.commits[0])}}"
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{github.event.after}}
      - name: Get Commit Message
        run: |
          MSG=$(git log --format=%B -n 1 ${{github.event.after}})
          echo "${MSG}"