name: CHANGE ME

on:
  pull_request:
    types:
      - labeled

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get PR labels
        id: pr-labels
        uses: joerick/pr-labels-action@v1.0.6
      - run: echo "HEY"
        if: contains(steps.pr-labels.outputs.labels, 'storefront')
      - run: echo "${{toJSON(github.event.commits[0])}}"