name: CHANGE ME

on:
  pull_request:
    types:
      - labeled

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get PR labels
        id: pr-labels
        uses: joerick/pr-labels-action@v1.0.6
      - uses: 8BitJonny/gh-get-current-pr@2.1.1
        id: PR
      - run: echo "PR ${prNumber} ${prTitle} at ${prUrl} is ${prJSON}"
          