name: CHANGE ME

on:
  pull_request:
    types:
      - labeled

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy storefront
        if: github.event.label.name == 'storefront'
        run: echo "${{ github.event.label.name }} 1"
