name: CHANGE ME

on:
  label:
    types: [edited]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Heelou"
      - name: Labeled to preview
        id: haslabel
        uses: DanielTamkin/HasLabel@v1.0.4
        with:
          contains: 'preview'
      - name: Test action
        if: steps.haslabel.outputs.labeled-preview
        run: echo 'This pull_request has this label.'