name: CHANGE ME

on:
  pull_request:
    types:
      - labeled

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get PR labels
        id: pr-labels
        uses: joerick/pr-labels-action@v1.0.6
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get Commit Message
        run: echo "$(git log -2 --format=%s)"